### ISSUE TITLE
image/jpg is not a valid type

### ISSUE THREAD

**Issue by mifi** [feross/capture-frame#1]
The correct type is image/jpeg. I tried running this, and it actually gives image/png data instead, when using format=jpg. Has this ever been working?

See:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL

See also:
https://github.com/mifi/lossless-cut/issues/25

**Comment by feross** [comment]
You are correct. This was not working before. We were only testing 'png', so this slipped through.

This is now fixed and released as 1.0.1. I also added tests to prevent a regression in the future 👍
